// src/modules/notifications/services/notification.service.js
const { AppDataSource } = require("../../../db/datasource");

class NotificationService {
  constructor() {
    this.notificationRepo = null;
  }

  async initialize() {
    if (this.notificationRepo) return;
    const { NotificationEntity } = require("../entities/notification.entity");
    this.notificationRepo = AppDataSource.getRepository(NotificationEntity);
    console.log("NotificationService initialized");
  }

  async getRepositories() {
    if (!this.notificationRepo) await this.initialize();
    return { notification: this.notificationRepo };
  }

  async _getRepository(queryRunner = null) {
    if (queryRunner) {
      const { NotificationEntity } = require("../entities/notification.entity");
      return queryRunner.manager.getRepository(NotificationEntity);
    }
    return (await this.getRepositories()).notification;
  }

  async _save(repo, entity, queryRunner = null, currentUser = null) {
    const { saveDb } = require("../../../common/utils/dbUtils/dbActions");
    if (queryRunner) {
      return await saveDb(queryRunner.manager, entity, { user: currentUser });
      // return await queryRunner.manager.save(entity);
    }
    return await saveDb(repo, entity, { user: currentUser });
  }

  async _update(repo, entity, queryRunner = null, currentUser = null) {
    const { updateDb } = require("../../../common/utils/dbUtils/dbActions");
    if (queryRunner) {
      return await updateDb(queryRunner.manager, entity, { user: currentUser });
      // return await queryRunner.manager.save(entity);
    }
    return await updateDb(repo, entity, { user: currentUser });
  }

  async _remove(repo, entity, queryRunner = null, currentUser = null) {
    const { removeDb } = require("../../../common/utils/dbUtils/dbActions");
    if (queryRunner) {
      return await removeDb(queryRunner.manager, entity, { user: currentUser });
      // return await queryRunner.manager.remove(entity);
    }

    return await removeDb(repo, entity, { user: currentUser });
  }

  /**
   * Create a new notification (auto‑generated by backend)
   * @param {Object} data - { userId, title, message, type?, metadata? }
   * @param {Object} user - logged-in user object
   * @param {Object} queryRunner - optional transaction runner
   */
  async create(data, user, queryRunner = null) {
    const auditLogger = require("../../../common/utils/auditLogger");
    const repo = await this._getRepository(queryRunner);

    if (!data.title) throw new Error("Notification title is required");
    if (!data.message) throw new Error("Notification message is required");

    const notification = repo.create({
      title: data.title,
      message: data.message,
      type: data.type || "info",
      metadata: data.metadata || null,
      isRead: false,
      createdAt: new Date(),
    });

    const saved = await this._save(repo, notification, queryRunner, user);
    await auditLogger.logCreate("Notification", saved.id, saved, user.id);
    return saved;
  }

  /**
   * Find notification by ID
   * @param {number} id
   */
  async findById(id) {
    const repo = await this._getRepository();
    const notification = await repo.findOne({ where: { id } });
    if (!notification) throw new Error(`Notification with ID ${id} not found`);
    return notification;
  }

  /**
   * Find all notifications with filters and pagination
   * @param {Object} options
   * @param {number} [options.page=1]
   * @param {number} [options.limit=10]
   * @param {boolean} [options.isRead]
   * @param {string} [options.type]
   * @param {string} [options.sortBy='createdAt']
   * @param {string} [options.sortOrder='DESC']
   */
  async findAll(options = {}) {
    const repo = await this._getRepository();
    const {
      page = 1,
      limit = 10,
      isRead,
      type,
      sortBy = "createdAt",
      sortOrder = "DESC",
    } = options;

    const qb = repo.createQueryBuilder("notification");

    if (isRead !== undefined) {
      qb.andWhere("notification.isRead = :isRead", { isRead });
    }
    if (type) {
      qb.andWhere("notification.type = :type", { type });
    }

    const order = sortOrder.toUpperCase() === "ASC" ? "ASC" : "DESC";
    qb.orderBy(`notification.${sortBy}`, order);

    const skip = (page - 1) * limit;
    qb.skip(skip).take(limit);

    const [data, total] = await qb.getManyAndCount();

    return {
      data,
      total,
      page: Number(page),
      limit: Number(limit),
      totalPages: Math.ceil(total / limit),
    };
  }

  /**
   * Mark a single notification as read (or unread)
   * @param {number} id
   * @param {boolean} isRead
   * @param {Object} user
   * @param {Object} queryRunner
   */
  async markAsRead(id, isRead = true, user, queryRunner = null) {
    const auditLogger = require("../../../common/utils/auditLogger");
    const repo = await this._getRepository(queryRunner);

    const notification = await repo.findOne({ where: { id } });
    if (!notification) throw new Error(`Notification with ID ${id} not found`);

    const oldData = { ...notification };
    notification.isRead = isRead;
    notification.updatedAt = new Date();

    const saved = await this._update(repo, notification, queryRunner, user);
    await auditLogger.logUpdate("Notification", id, oldData, saved, user.id);
    return saved;
  }

  /**
   * Mark all notifications as read
   * @param {Object} user
   * @param {Object} queryRunner
   */
  async markAllAsRead(user, queryRunner = null) {
    const auditLogger = require("../../../common/utils/auditLogger");
    const repo = await this._getRepository(queryRunner);

    const result = await repo
      .createQueryBuilder()
      .update()
      .set({ isRead: true, updatedAt: new Date() })
      .where("isRead = :isRead", { isRead: false })
      .execute();

    const count = result.affected || 0;
    if (count > 0) {
      await auditLogger.logUpdate(
        "Notification",
        null,
        { isRead: false },
        { isRead: true },
        user.id
      );
    }
    return count;
  }

  /**
   * Delete a notification (hard delete)
   * @param {number} id
   * @param {Object} user
   * @param {Object} queryRunner
   */
  async delete(id, user, queryRunner = null) {
    const auditLogger = require("../../../common/utils/auditLogger");
    const repo = await this._getRepository(queryRunner);

    const notification = await repo.findOne({ where: { id } });
    if (!notification) throw new Error(`Notification with ID ${id} not found`);

    await this._remove(repo, notification, queryRunner, user);
    await auditLogger.logDelete("Notification", id, notification, user.id);
    return { success: true };
  }

  /**
   * Get unread count
   */
  async getUnreadCount() {
    const repo = await this._getRepository();
    return repo.count({ where: { isRead: false } });
  }

  /**
   * Get notification statistics
   */
  async getStats() {
    const repo = await this._getRepository();

    const total = await repo.count();
    const unread = await repo.count({ where: { isRead: false } });
    const read = total - unread;

    const typeCounts = await repo
      .createQueryBuilder("notification")
      .select("notification.type", "type")
      .addSelect("COUNT(*)", "count")
      .groupBy("notification.type")
      .getRawMany();

    const byType = typeCounts.reduce((acc, row) => {
      acc[row.type] = parseInt(row.count, 10);
      return acc;
    }, {});

    return { total, unread, read, byType };
  }
}

const notificationService = new NotificationService();
module.exports = notificationService;
